import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {readFile,writeFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {malformed,wrap,node} from './chromium-cases.mjs';
const out=process.env.B2_RUN;
assert.ok(out);
await build({entryPoints:['src/lib/chromiumBookmarks.ts'],bundle:true,platform:'node',format:'cjs',outfile:out+'/parser.cjs'});
const {parseChromiumBookmarks:parse}=createRequire(import.meta.url)(out+'/parser.cjs');
const raw=await readFile('tests/fixtures/chromium-bookmarks.json','utf8');
const parsed=parse(raw);
assert.equal(parsed.error,undefined);assert.equal(parsed.posts.length,3);assert.equal(parsed.duplicates,1);assert.equal(parsed.unsupported,1);
assert.equal(parsed.posts[1].title,'Programming JavaScript tutorial — supplied');
assert.equal(parsed.posts[2].title,'Cooking recipe kitchen — supplied');
assert.ok(parsed.posts.every(p=>p.source==='browser'&&!p.thumbnailUrl));
assert.equal(parsed.posts[1].canonicalUrl,'https://native.example.invalid/programming?lesson=1&lesson=2#code');
const invalid=malformed.map(([name,raw])=>{const r=parse(raw);assert.ok(r.error,name);assert.deepEqual(r.posts,[],name);return {name,error:r.error,status:'PASS'};});
const urls=['https://example.invalid/a#x','https://example.invalid/a#y','https://example.invalid/?q=1&q=2','https://example.invalid/?q=2','https://example.invalid/中文'];
const identity=parse(wrap(urls.map(u=>node(u))));assert.equal(identity.posts.length,5);assert.equal(new Set(identity.posts.map(p=>p.id)).size,5);
assert.deepEqual(identity.posts.map(p=>p.canonicalUrl),urls.map(u=>new URL(u).href));
let deep=node('https://example.invalid/deep');for(let i=0;i<250;i++)deep={type:'folder',children:[deep]};assert.equal(parse(wrap([deep])).posts.length,1);
assert.equal(parse('\uFEFF'+raw).posts.length,3);
await writeFile(out+'/unit.json',JSON.stringify({status:'PASS',parsed,invalid,identity,deepFolders:250,bom:true},null,2));
console.log('PASS parser: 3 unique, duplicate1, unsupported1; 15 controlled failures; query/fragment/unicode/250 folders/BOM');
