"""Reproducible Inno Setup build wrapper for the per-user Windows installer (B6).

Packages the ALREADY-VERIFIED standalone runtime in dist-standalone-v<version>/SuperBookmarkManager/.
It never rebuilds application source. Before compiling it re-verifies the input artifact
hashes against the complete receipt generated by the standalone build; any mismatch aborts
the build so a silently-changed runtime can never be packaged invisibly.

Exact equivalent command (run from the repository root with any Python 3.12):

    python packaging/build_installer.py

Output: dist-installer-v<version>/SuperBookmarkManager-Setup.exe (does NOT touch dist-standalone/).
"""
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
from payload_hygiene import scan
from release_paths import CANDIDATE, VERSION

ROOT = Path(__file__).resolve().parents[1]
STANDALONE = ROOT / f"dist-standalone-{CANDIDATE}" / "SuperBookmarkManager"
OUTPUT_DIR = ROOT / f"dist-installer-{CANDIDATE}"
ISS = ROOT / "packaging" / "installer.iss"
APP_VERSION = VERSION

def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def find_iscc() -> str:
    candidates = [
        Path(os.environ["LOCALAPPDATA"]) / "Programs" / "Inno Setup 6" / "ISCC.exe",
        Path(r"C:/Program Files (x86)/Inno Setup 6/ISCC.exe"),
        Path(r"C:/Program Files/Inno Setup 6/ISCC.exe"),
    ]
    for c in candidates:
        if c.is_file():
            return str(c)
    found = shutil.which("iscc") or shutil.which("ISCC")
    if found:
        return found
    raise SystemExit("ISCC.exe not found. Install Inno Setup 6 (winget install JRSoftware.InnoSetup).")


def verify_input() -> None:
    if not (STANDALONE / "SuperBookmarkManager.exe").is_file():
        raise SystemExit(f"Standalone runtime missing at {STANDALONE}. Build it first (packaging/build_standalone.py).")
    scan(STANDALONE)  # before any payload hashes
    receipt_path = STANDALONE.parent / "build-receipt.json"
    if not receipt_path.is_file():
        raise SystemExit("Missing standalone build receipt; rebuild from source first.")
    receipt = json.loads(receipt_path.read_text())
    actual_files = {p.relative_to(STANDALONE).as_posix() for p in STANDALONE.rglob("*") if p.is_file()}
    if actual_files != set(receipt):
        raise SystemExit("Standalone file set differs from build receipt.")
    for rel, expected in receipt.items():
        if Path(rel).is_absolute() or ".." in Path(rel).parts or sha256(STANDALONE / rel) != expected:
            raise SystemExit("Standalone receipt mismatch: " + rel)
    assets = list((ROOT / "frontend/dist").rglob("*")) + [ROOT / "LICENSE", ROOT / "THIRD_PARTY_LICENSES.md"]
    assets += list((ROOT / "third_party_notices").rglob("*"))
    for source in assets:
        if source.is_file():
            bundled = STANDALONE / "_internal" / source.relative_to(ROOT)
            if not bundled.is_file() or sha256(source) != sha256(bundled):
                raise SystemExit("Current source asset differs from bundle: " + source.relative_to(ROOT).as_posix())
    print(f"Input verification PASS: {len(receipt)} payload files match build receipt and current assets.")

def main() -> int:
    if OUTPUT_DIR.exists():
        raise SystemExit("Candidate installer output already exists; preserve it and select a new output directory.")
    verify_input()
    iscc = find_iscc()
    print(f"ISCC: {iscc}")
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    args = [
        iscc,
        f"/DStandaloneDir={STANDALONE}",
        f"/DOutputDir={OUTPUT_DIR}",
        f"/DAppVersion={APP_VERSION}",
        str(ISS),
    ]
    print("Running:", " ".join(f'"{a}"' if " " in a else a for a in args))
    proc = subprocess.run(args, capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    if proc.returncode != 0:
        raise SystemExit(f"ISCC failed with exit code {proc.returncode}.")
    setup = OUTPUT_DIR / "SuperBookmarkManager-Setup.exe"
    if not setup.is_file():
        raise SystemExit("ISCC reported success but the setup exe was not produced.")
    digest = sha256(setup)
    size = setup.stat().st_size
    setup.with_suffix(".exe.sha256").write_text(f"{digest}  {setup.name}\n", encoding="ascii")
    print(f"OUTPUT: {setup}")
    print(f"OUTPUT_SHA256: {digest}")
    print(f"OUTPUT_BYTES: {size}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

